### ISSUE TITLE
Duplication requests routing to wrong Aeon queues

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/request_broker#83] opened 2021-01-04 17:55 UTC
## Describe the bug
Duplication requests are not being routed to Aeon correctly. They should be routed to 2 locations: `Awaiting Request Processing` and `Awaiting Photoduplication Processing`, but they are currently being routed into `Awaiting Using Review` and `Awaiting Photoduplication`.

## Additional context
As reported by the Reference Team.

**Comment by HaSistrunk** [comment] 2021-01-15 19:25
Examples provided by Reference staff: 
1. `/objects/gREB5kjDtHovr3RBB3HbwM`(/repositories/2/archival_objects/949240)
![image](https://user-images.githubusercontent.com/15254041/104769492-612ea300-573d-11eb-8850-adad863bb9fb.png)

2. `/objects/hoZieLCCs5ReTJSHroo3qN` (/repositories/2/archival_objects/1018765)
![image](https://user-images.githubusercontent.com/15254041/104769564-7b688100-573d-11eb-9e5b-9fbee125ae52.png)

**Comment by helrond** [comment] 2021-01-18 19:34
Parsing the error report a bit, it seems like the issue being reported is that requests end up in `Awaiting User Review` rather than `Awaiting Request Processing`. I continue to be unable to reproduce this. 

Here is what I did:
- Spin up the development branch of Request Broker locally
- Spin up a local instance of DIMES (changing the value of `REACT_APP_REQUEST_BROKER_BASEURL` to `http://localhost:8000/api` first)
- Add `/objects/gREB5kjDtHovr3RBB3HbwM` and `/objects/hoZieLCCs5ReTJSHroo3qN` to my list
- Submit a duplication request to Aeon

In both cases, I'm seeing this in RACcess:
<img width="968" alt="Screen Shot 2021-01-18 at 2 33 38 PM" src="https://user-images.githubusercontent.com/607621/104956488-33926580-599a-11eb-89a0-50e20053ca8b.png">

**Comment by HaSistrunk** [comment] 2021-01-19 17:29
This may have been fixed along the way... let's leave this open and see if it comes up again with more use? I'll communicate back to the Reference Team to report if this continues.

**Comment by helrond** [comment] 2021-01-19 20:09
Closing this for now, since it doesn't seem to be an issue.

**Closed as completed by helrond** 2021-01-19 20:09 UTC
